# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Install-Exchange.ps1
. $PSScriptRoot\Install-PreRequisites.ps1
. $PSScriptRoot\Set-ClientAccess.ps1
. $PSScriptRoot\Set-MailBoxDatabase.ps1
. $PSScriptRoot\Set-Transport.ps1
. $PSScriptRoot\Sync-ClientAccess.ps1
. $PSScriptRoot\Sync-MailBox.ps1
. $PSScriptRoot\Sync-Transport.ps1
. $PSScriptRoot\Test-MailFlow.ps1
. $PSScriptRoot\Uninstall-OldExchange.ps1
